plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.cincoregioes.formacaocidada'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.cincoregioes.formacaocidada'
        minSdk 23
        targetSdk 35
        versionCode 19
        versionName '1.9'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            debuggable false
        }
    }
}
